name: products
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for broader compatibility

dependencies:
  flutter:
    sdk: flutter

  # UI and State Management
  cupertino_icons: ^1.0.8
  provider: ^6.1.2 # Updated to a recent stable version
  intl: ^0.19.0 # Updated to a recent stable version
  google_fonts: ^6.2.1 # Updated to a recent stable version
  fl_chart: ^0.68.0 # Updated to a recent stable version

  # Local Storage
  shared_preferences: ^2.2.3 # Updated to a recent stable version

  # Firebase Packages - Versions aligned for compatibility
  firebase_core: ^3.1.0 # Updated to a recent stable version
  firebase_auth: ^5.1.0 # Updated to a recent stable version
  cloud_firestore: ^5.0.1 # Updated to a recent stable version
  firebase_database: ^11.0.1 # ADDED: For Realtime Database functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to a recent stable version

flutter:
  uses-material-design: true
  assets:
    - assets/