// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PiSOnfzZiGZUJebgrTQtvwg6PO8k8dk',
    appId: '1:1056964274932:web:46396c86c41ab6b98f4ca1',
    messagingSenderId: '1056964274932',
    projectId: 'jujumomoyoyo',
    authDomain: 'jujumomoyoyo.firebaseapp.com',
    storageBucket: 'jujumomoyoyo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEyZ004Gf1Dd8plN-L-gwODw2BHDNZE38',
    appId: '1:1056964274932:android:b53927c29cace0688f4ca1',
    messagingSenderId: '1056964274932',
    projectId: 'jujumomoyoyo',
    storageBucket: 'jujumomoyoyo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6PiSOnfzZiGZUJebgrTQtvwg6PO8k8dk',
    appId: '1:1056964274932:web:6adaef6787d729ac8f4ca1',
    messagingSenderId: '1056964274932',
    projectId: 'jujumomoyoyo',
    authDomain: 'jujumomoyoyo.firebaseapp.com',
    storageBucket: 'jujumomoyoyo.firebasestorage.app',
  );
}
